apiVersion: v1
kind: Service
metadata:
  name: {{ include "hoppscotch-aio.fullname" . }}-api
  labels:
    {{- include "hoppscotch-aio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceApi.type }}
  ports:
    - port: {{ .Values.serviceApi.port }}
      targetPort: httpapi
      protocol: TCP
      name: http
  selector:
    {{- include "hoppscotch-aio.selectorLabels" . | nindent 4 }}
