apiVersion: v1
kind: Service
metadata:
  name: {{ include "hoppscotch-aio.fullname" . }}-admin
  labels:
    {{- include "hoppscotch-aio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceAdmin.type }}
  ports:
    - port: {{ .Values.serviceAdmin.port }}
      targetPort: httpadmin
      protocol: TCP
      name: http
  selector:
    {{- include "hoppscotch-aio.selectorLabels" . | nindent 4 }}
